name: Docker

on:
  workflow_call:

jobs:

  docker:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Setup Docker build
      uses: docker/setup-buildx-action@v3.6.1
    
    - name: Docker Login 
      uses: docker/login-action@v2.0.0 
      with: 
        username: igoraugustoi
        password: $PASSWORD
