name: Docker

on:
  workflow_call:

jobs:

  docker:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Setup Docker build
      uses: docker/setup-buildx-action@v3.6.1
    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        username: igoraugustoi
        password: ${{ secrets.PASSWORD_DOCKER_HUB }}
    - name: Build and push Docker images
      uses: docker/build-push-action@v6.5.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: igoraugustoi/go_ci:${{ github.ref_name }}
                    
        
